steps:
# -------------------------
# Build train image  
# -------------------------
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-f', 'dockerfiles/train.dockerfile',
      '-t', 'europe-west1-docker.pkg.dev/active-premise-484209-h0/my-container-repo/train:manual-2',
      '.'
    ]

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'europe-west1-docker.pkg.dev/active-premise-484209-h0/my-container-repo/train:manual-2'
    ]

# -------------------------
# Build evaluate image
# -------------------------
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-f', 'dockerfiles/evaluate.dockerfile',
      '-t', 'europe-west1-docker.pkg.dev/active-premise-484209-h0/my-container-repo/evaluate:manual',
      '.'
    ]

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'europe-west1-docker.pkg.dev/active-premise-484209-h0/my-container-repo/evaluate:manual'
    ]

# -------------------------
# Build api image
# -------------------------
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-f', 'dockerfiles/api.dockerfile',
      '-t', 'europe-west1-docker.pkg.dev/active-premise-484209-h0/my-container-repo/api:manual',
      '.'
    ]

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'europe-west1-docker.pkg.dev/active-premise-484209-h0/my-container-repo/api:manual'
    ]
  
# -------------------------
# Build frontend image
# -------------------------
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-f', 'dockerfiles/frontend.dockerfile',
      '-t', 'europe-west1-docker.pkg.dev/active-premise-484209-h0/my-container-repo/frontend:manual',
      '.'
    ]

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'europe-west1-docker.pkg.dev/active-premise-484209-h0/my-container-repo/frontend:manual'
    ]

options:
  logging: CLOUD_LOGGING_ONLY   # optional, can still log to Cloud Logging

