# cloudbuild.yaml
# Build and push train + evaluate Docker images to Artifact Registry
# Using explicit dir: to handle Dockerfiles in subfolders
# Registry: europe-west1

steps:
  # -------------------------
  # 1️⃣ Build & push train image
  # -------------------------
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/active-premise-484209-h0/my-container-repo/mlopsproject/train:e86ff6c14f25cccae4b4d48e3a592992af9c4c6a', '-f', 'dockerfiles/train.Dockerfile', '.'] # Assuming you want to use 'my-container-repo'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-west1-docker.pkg.dev/active-premise-484209-h0/my-container-repo/mlopsproject/train:e86ff6c14f25cccae4b4d48e3a592992af9c4c6a'
      ]

  # -------------------------
  # 2️⃣ Build & push evaluate image
  # -------------------------
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/active-premise-484209-h0/my-container-repo/mlopsproject/evaluate:e86ff6c14f25cccae4b4d48e3a592992af9c4c6a', '-f', 'dockerfiles/evaluate.Dockerfile', '.'] # Using 'api.Dockerfile' as 'evaluate.Dockerfile' was not in your dir structure

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-west1-docker.pkg.dev/active-premise-484209-h0/my-container-repo/mlopsproject/evaluate:e86ff6c14f25cccae4b4d48e3a592992af9c4c6a'
      ]
