# cloudbuild.yaml
# Build, tag, and push train and evaluate Docker images to Artifact Registry
# Timestamp-based versioning for reproducibility

steps:
  # -------------------------
  # 1️⃣ Build & push the training image with timestamp
  # -------------------------
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Generate timestamp: YYYYMMDD_HHMMSS
        timestamp=$(date +%Y%m%d_%H%M%S)
        echo "Building train image with tag: $timestamp"

        # Build train image
        docker build \
          -t us-central1-docker.pkg.dev/active-premise-484209-h0/my-container-repo/train:$timestamp \
          -f train.dockerfile .

        # Push train image
        docker push us-central1-docker.pkg.dev/active-premise-484209-h0/my-container-repo/train:$timestamp

  # -------------------------
  # 2️⃣ Build & push the evaluation image with timestamp
  # -------------------------
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Generate timestamp: YYYYMMDD_HHMMSS
        timestamp=$(date +%Y%m%d_%H%M%S)
        echo "Building evaluate image with tag: $timestamp"

        # Build evaluate image
        docker build \
          -t us-central1-docker.pkg.dev/active-premise-484209-h0/my-container-repo/evaluate:$timestamp \
          -f evaluate.dockerfile .

        # Push evaluate image
        docker push us-central1-docker.pkg.dev/active-premise-484209-h0/my-container-repo/evaluate:$timestamp

# -------------------------
# Optional: images field removed
# -------------------------
# Since tags are dynamic (timestamps), the 'images:' section cannot list exact tags.
# You can leave it out or list generic references if desired.
