steps:
  # -------------------------
  # 1️⃣ Build & push train image
  # -------------------------
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'europe-west1-docker.pkg.dev/active-premise-484209-h0/my-container-repo/train:latest',
        '-f', 'dockerfiles/train.dockerfile',
        '.'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-west1-docker.pkg.dev/active-premise-484209-h0/my-container-repo/train:latest'
      ]

  # -------------------------
  # 2️⃣ Build & push evaluate image
  # -------------------------
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'europe-west1-docker.pkg.dev/active-premise-484209-h0/my-container-repo/evaluate:latest',
        '-f', 'dockerfiles/evaluate.dockerfile',
        '.'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-west1-docker.pkg.dev/active-premise-484209-h0/my-container-repo/evaluate:latest'
      ]

images:
  - 'europe-west1-docker.pkg.dev/active-premise-484209-h0/my-container-repo/train:latest'
  - 'europe-west1-docker.pkg.dev/active-premise-484209-h0/my-container-repo/evaluate:latest'
