# cloudbuild.yaml
# Build, tag, and push train and evaluate Docker images to Artifact Registry
# Unified timestamp across images and model versions

steps:
  # -------------------------
  # 1️⃣ Generate a unified timestamp
  # -------------------------
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Create a timestamp: YYYYMMDD_HHMMSS
        MODEL_TIMESTAMP=$(date +%Y%m%d_%H%M%S)
        echo "Unified timestamp for this build: $MODEL_TIMESTAMP"

        # Save it to a file to pass to subsequent steps
        echo $MODEL_TIMESTAMP > timestamp.txt

  # -------------------------
  # 2️⃣ Build & push train image
  # -------------------------
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        MODEL_TIMESTAMP=$(cat timestamp.txt)
        echo "Building train image with tag: $MODEL_TIMESTAMP"

        docker build \
          --build-arg MODEL_TIMESTAMP=$MODEL_TIMESTAMP \
          -t us-central1-docker.pkg.dev/active-premise-484209-h0/my-container-repo/train:$MODEL_TIMESTAMP \
          -f dockerfiles/train.dockerfile .

        docker push us-central1-docker.pkg.dev/active-premise-484209-h0/my-container-repo/train:$MODEL_TIMESTAMP

  # -------------------------
  # 3️⃣ Build & push evaluate image
  # -------------------------
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        MODEL_TIMESTAMP=$(cat timestamp.txt)
        echo "Building evaluate image with tag: $MODEL_TIMESTAMP"

        docker build \
          --build-arg MODEL_TIMESTAMP=$MODEL_TIMESTAMP \
          -t us-central1-docker.pkg.dev/active-premise-484209-h0/my-container-repo/evaluate:$MODEL_TIMESTAMP \
          -f dockerfiles/evaluate.dockerfile .

        docker push us-central1-docker.pkg.dev/active-premise-484209-h0/my-container-repo/evaluate:$MODEL_TIMESTAMP

# Note: 'images' section is omitted because tags are dynamic
