steps:
  # Build & push train image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-f', 'dockerfiles/train.dockerfile',
        '-t', 'europe-west1-docker.pkg.dev/active-premise-484209-h0/my-container-repo/train:latest',
        '.'   # <-- build context should be repo root
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-west1-docker.pkg.dev/active-premise-484209-h0/my-container-repo/train:latest'
      ]

  # Build & push evaluate image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-f', 'dockerfiles/evaluate.dockerfile',
        '-t', 'europe-west1-docker.pkg.dev/active-premise-484209-h0/my-container-repo/evaluate:latest',
        '.'   # <-- build context should be repo root
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-west1-docker.pkg.dev/active-premise-484209-h0/my-container-repo/evaluate:latest'
      ]

images:
  - 'europe-west1-docker.pkg.dev/active-premise-484209-h0/my-container-repo/train:latest'
  - 'europe-west1-docker.pkg.dev/active-premise-484209-h0/my-container-repo/evaluate:latest'
